FROM python:3.12-slim@sha256:a4d50ac833bbe134fb7367e9a88644641d949ffeeb42acdb762e25a32b2d3dae

ENV API_URL="https://kubernetes.default.svc/"
ENV NAMESPACE="gitlab"
ENV MAX_HOURS="1"
ENV POD_STATUS="Succeeded, Failed"
ENV TOKEN=""
ENV STARTS_WITH="runner-"

ENV PYTHONUNBUFFERED=0
ENV PYDEVD_DISABLE_FILE_VALIDATION=1

WORKDIR /app
COPY ./app/ ./
COPY requirements-dev.txt ./

RUN pip install --no-cache-dir -r requirements-dev.txt
USER 1
CMD ["/usr/local/bin/python", "/app/clean.py"]
