FROM python:3.12-slim@sha256:5c73034c2bc151596ee0f1335610735162ee2b148816710706afec4757ad5b1e

ENV API_URL="https://kubernetes.default.svc/"
ENV NAMESPACE="gitlab"
ENV MAX_HOURS="1"
ENV POD_STATUS="Succeeded, Failed"
ENV TOKEN=""
ENV STARTS_WITH="runner-"

ENV PYTHONUNBUFFERED=0
ENV PYDEVD_DISABLE_FILE_VALIDATION=1

WORKDIR /app
COPY ./app/ ./
COPY requirements-dev.txt ./

RUN pip install --no-cache-dir -r requirements-dev.txt
USER 1
CMD ["/usr/local/bin/python", "/app/clean.py"]
