resources:
  - cronjob.yaml
  - role.yaml
namespace: gitlab

images:
  - name: cleanup-gitlab
    newName: ghcr.io/azman0101/clean-pods
    newTag: master@sha256:66eeb429fea219d81f7e29631e3f4fb8c29a143c94bfd5603adefaeb3b2daf54
