resources:
  - cronjob.yaml
  - role.yaml
namespace: gitlab

images:
  - name: cleanup-gitlab
    newName: ghcr.io/azman0101/clean-pods
    newTag: master@sha256:e49bdd0fea7d44874d9bf991cab475e3ec2130c45b9c6b4631d2dba30fdf6f7c
