apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: clean-pod-role
  namespace: gitlab
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
  # add pod/status for checking pod status
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods/status"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: clean-pod-role
  namespace: gitlab
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: pod-cleanup # "name" is case sensitive
  namespace: gitlab
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: clean-pod-role # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-cleanup
  namespace: gitlab
